### ISSUE TITLE
if message is long, how to make message's tooltip showing next to chat box 

### ISSUE THREAD

**Issue by ibrahim-nazari** [ReactTooltip/react-tooltip#1186] opened 2024-04-10 04:48 UTC
if a message content is big, inside the chat box right now the message's tooltip show far a way from  chat screen, how to make it, like it should always show near to the chat screen(if message is big) ideally like Facebook do for message's tooltip
the tooltip position is fixed, we want to show tooltip outside the box as well
here is the link if you guys want to experiment : https://www.convose.com/

![tooltipmessage](https://github.com/ReactTooltip/react-tooltip/assets/51007186/6ee0f268-112e-456e-877f-160d245754f5)

**Comment by gabrieljablonski** [comment] 2024-04-10 16:54
This will depend heavily on your design decisions. My first suggestion is to use the `place` option with `left-end` (see [the docs](https://react-tooltip.com/docs/options#:~:text=Check%20the%20examples-,place,-string) for more info). This should improve the tooltip placement a bit (it will still move around when you scroll on a long message).

---

On another note, if I'm not mistaken, you're using tooltip components for each anchor element, so you might want to check this section on our troubleshooting page.

https://react-tooltip.com/docs/troubleshooting#dynamically-generated-anchor-elements

This video doesn't capture it super well, but I'm noticing a "rogue" tooltip showing up randomly when hovering/unhovering on elements that have a tooltip. You might be able to test this yourself.

https://github.com/ReactTooltip/react-tooltip/assets/21102974/3f310377-7a95-42f1-a76e-66ecba4cc46c

Using multiple tooltip components isn't the cause of this bug, but using a single tooltip for your whole application (or at least only a handful) helps mitigating these kinds of bugs.

**Comment by ibrahim-nazari** [comment] 2024-04-11 02:09
- ("rogue" tooltip showing up randomly), checked troubleshot link, thanks, it will fix the problem.

- data-tooltip-place is not working for us, when user scroll down we see tooltip showing far from the bottom of chat screen, ( chats don't open always on bottom of screen), like in the screen shot bellow. ideally the tooltip should appear always near to the chat screen area (bellow screen shot red box)
![image](https://github.com/ReactTooltip/react-tooltip/assets/51007186/ab947b70-afe4-480d-a326-ba2c8a902e6e)

**Comment by gabrieljablonski** [comment] 2024-04-11 02:18
There's definitely a way to achieve what you're trying, it's just not so obvious to me right now how to do it.

I'll have to come back to this when I have the time, might be able to suggest something. Let me know if you figure out anything.

**Comment by gabrieljablonski** [comment] 2024-04-13 16:42
This is a very hard thing to accomplish due to how the tooltip works internally. The best I could come up with is the following example:

https://stackblitz.com/edit/vitejs-vite-fsaxej?file=src%2FApp.tsx

The main thing here is to keep the tooltip inside the scrollable element (the chat box in your case), and add `position: relative` to it, so the tooltip stays inside it.

You also need to override the default `floating-ui` middlewares.

```tsx
import { offset, flip, shift } from '@floating-ui/dom';

<Tooltip  middlewares={[offset(10), flip(), shift({ padding: 300 })]} />
```

(`padding: 300` on the `shift` middleware is roughly half the height of the scrollable element on the example, you may need to play around with the value to get the tooltip to stay centered on the chat box)

Still, you'll run into the issue of the tooltip getting clipped if the container is not wide enough.

![image](https://github.com/ReactTooltip/react-tooltip/assets/21102974/3b675ba2-8c8a-4b0b-bd76-da51453675dc)

-----

As I've said before, it's definitely doable, but pretty hard to achieve due to how `react-tooltip` works.

I'll keep this open for now if you want to share any findings, but I'd suggest trying a different approach for displaying the tooltip on the messages.

**Comment by gabrieljablonski** [comment] 2024-04-28 00:21
Closing this for now.

Feel free to reopen if you have more information to add.

**Closed by gabrieljablonski** 2024-04-28 00:21 UTC
Labels: Question, Information Needed
