### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getAttribute' of null

### ISSUE THREAD

**Issue by Springbach** [ReactTooltip/react-tooltip#312] opened 2017-06-22 20:13 UTC
bundle.js:13915 Uncaught TypeError: Cannot read property 'getAttribute' of nulltarget.isCapture @ bundle.js:13915addScrollListener @ bundle.js:13464(anonymous function) @ bundle.js:13348renderComponent @ bundle.js:2182rerender @ bundle.js:1909

source map

exports.default = function (target) {
	  target.prototype.isCapture = function (currentTarget) {
	    var dataIsCapture = currentTarget.getAttribute('data-iscapture');
	    return dataIsCapture && dataIsCapture === 'true' || this.props.isCapture || false;
	  };

please help

**Comment by samsiu** [comment] 2017-09-29 09:25
I believe this has to do with react nullifying the event object after setState. see: https://github.com/facebook/react/issues/2850
The recommended way is to cache the e.currentTarget to component's state, I think.

**Comment by alex-shamshurin** [comment] 2017-10-11 17:50
The same issue is here. Can we replace `currentTarget` with `target` as temporary workaround?

**Comment by occamsraiser** [comment] 2017-10-21 00:25
I'm seeing this problem as well.

**Comment by alex-shamshurin** [comment] 2017-10-21 09:28
@occamsraiser Try this fork https://www.npmjs.com/package/react-tooltip-currenttarget

**Comment by occamsraiser** [comment] 2017-10-23 16:19
@alex-shamshurin I tried it out -- I get a `Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null` from getPosition.js in this fork

**Comment by alex-shamshurin** [comment] 2017-10-24 09:43
@occamsraiser , I use this fork in production and get no errors.  My fork fixed only one issue here

```
  /**
   * Add scroll eventlistener when tooltip show
   * automatically hide the tooltip when scrolling
   */
  addScrollListener (e) {
    const isCaptureMode = this.isCapture(e.target)
    window.addEventListener('scroll', this.hideTooltip, isCaptureMode)
  }

```

not other issues related with the topic, your problem is related with the same reason (react lose currentTarget after setState callback). I'll try to fix it on fork.

**Comment by alex-shamshurin** [comment] 2017-10-24 12:40
@occamsraiser I have updated to 3.3.4 and then got the error. So 3.3.4 is broken, I will fix it, but 3.3.3 works normally

**Comment by alex-shamshurin** [comment] 2017-10-25 08:52
I've just released 3.3.5 https://www.npmjs.com/package/react-tooltip-currenttarget and the issue is fixed, try it and please report and I make a PR to main package

**Comment by occamsraiser** [comment] 2017-10-25 16:56
@alex-shamshurin, 3.3.5 works great. Thanks for fixing the issue!

**Comment by occamsraiser** [comment] 2017-10-31 23:53
@alex-shamshurin, Do you have a rough timeline on when your changes will be merged into the main package?

**Comment by alex-shamshurin** [comment] 2017-11-02 07:49
I'll make a PR this week. I do not know when it will be merged.

**Comment by occamsraiser** [comment] 2018-02-22 00:31
@wwayne any update on when some of these PRs will be merged into the main branch and released?

**Comment by renanborgez** [comment] 2018-05-29 20:17
@alex-shamshurin your fork is working like a charm, thanks 👍

**Comment by aronhelser** [comment] 2018-05-29 20:28
I don't see a PR by @alex-shamshurin either open or merged - am I just missing it? I've been helping out, and I'd be happy to see a fork get re-integrated....

**Comment by alex-shamshurin** [comment] 2018-05-30 09:26
As far as I remember It was merged.

**Comment by aronhelser** [comment] 2018-05-30 15:57
@renanborgez did you try the latest react-tooltip? Does it still have this issue? (from the code, I expect the issue to still be present). If so, I should be able to fix...

**Comment by renanborgez** [comment] 2018-05-30 18:33
@aronhelser yes, i just installed the extension yesterday and i got the error, because of that i was searching by a solution

**Comment by alex-shamshurin** [comment] 2018-05-31 07:53
It's really easy to debug. Please describe your case, stack trace...

**Closed** 2022-12-07 12:42 UTC
