### ISSUE TITLE
[BUG] flickering behaviour with data-tooltip-hidden

### ISSUE THREAD

**Issue by nsalamad** [ReactTooltip/react-tooltip#1114] opened 2023-11-06 20:25 UTC
**Bug description**
`data-tooltip-hidden={true}` results in flickering behaviour when mousing over from an element that has a visible tooltip. 

**Version of Package**
v5.22.0

**To Reproduce**
Hover from an anchor element that has `data-tooltip-hidden={false}`, to an element with `data-tooltip-hidden={true}`. You should see the tooltip for the element with `data-tooltip-hidden={true}` appear for a split second and then disappear.

CodeSandbox repro: https://codesandbox.io/s/admiring-shadow-ny25y8?file=/src/App.js
Odd numbered words have `data-tooltip-hidden` set to `false`. If you hover from an odd numbered word to an even numbered one, you will see the tooltip that should be hidden appear for a split second.

**Screenshots**
Video:

https://github.com/ReactTooltip/react-tooltip/assets/33500361/69d41343-079a-4ac3-bcc0-a63d0ea9d199

**Expected behavior**
When hovering from an anchor with a tooltip that has `data-tooltip-hidden` set to `false` to an anchor with a tooltip that is hidden, the hidden tooltip should not appear at all.

**Comment by marcantoinegodde** [comment] 2023-11-09 17:39
In my case, since 5.22.0 `data-tooltip-hidden={true}` isn't working at all. If I roll back to 5.21.7, everything works as expected.

I noticed another side-effect. If `data-tooltip-content` is equal to `null` or `undefined`, a small tooltip is rendered without anything in it and this shouldn't be the case. Nothing should happen on hover. Again, works as expected in 5.21.7.

**Comment by dsims01** [comment] 2023-11-09 20:43
Seems the issue is wider than just `data-tooltip-hidden`, bc I see the same flickering in @nsalamad's codesandbox when I remove `data-tooltip-hidden` and add `delayShow={1000}` as a Tooltip prop.

**Comment by gabrieljablonski** [comment] 2023-11-12 17:44
Sorry for the delay, for some reason I'm not receiving GitHub notifications for new issues anymore. Weird stuff.

All problems described here in the thread are very likely due to the new "fade-out" transition when closing the tooltip, which used to just abruptly close before v5.22.0.

I'll probably be able to reproduce it, but if you guys don't mind, @marcantoinegodde and @dsims01, please provide a CodeSandbox (or similar) reproducing the variations of the problem you've experienced. It will help a lot with debugging it.

**Comment by gabrieljablonski** [comment] 2023-11-12 18:15
The beta version `react-tooltip@5.22.1-beta.1118.0` fixes the problem with `hidden` and null/empty `content`.

@dsims01 the problem with `delayShow` will be a bit trickier to fix, I'll open a new issue to track it separately.

**Closed** 2023-11-13 17:32 UTC
Labels: Bug

**Comment by gabrieljablonski** [comment] 2023-11-13 17:57
Fixed on official release `react-tooltip@5.23.0` (alongside the new ["imperative mode"](https://react-tooltip.com/docs/examples/imperative-mode), check it out 😀😀)
