### ISSUE TITLE
Package breaks react testing library out of the box: Invalid insertion of STYLE node 

### ISSUE THREAD

**Issue by halented** [ReactTooltip/react-tooltip#681] opened 2021-03-12 18:36 UTC
In tooltip/src/index.js, on lines 202 - 208:
```javascript
if (!domRoot.querySelector('style[data-react-tooltip]')) {
      const style = document.createElement('style');
      style.textContent = baseCss;
      style.setAttribute('data-react-tooltip', 'true');

      domRoot.appendChild(style);
    }
  ```

When running any basic test using React Testing library on a page that has a Tooltip element, this produces the error: `HierarchyRequestError: Invalid insertion of STYLE node in #document node.`

I've tried manually adding the baseCss, manually adding style tag, and/or manually adding an attribute on the tooltip itself or its targeted JSX tag with `style={{'data-react-tooltip':true}}`, to no avail. Commenting out these lines in the package allows the testing suite to run fine, but I'm not sure how to arrange my code so that the querySelector returns a tag and avoids this code block inserting an invalid style node.

**Comment by lyndonmoore** [comment] 2021-03-15 06:13
Also having this problem while trying to update from Version `3.11.6` to `4.2.16` tests that were previously passing are now all failing with this error.

**Comment by hhorton2** [comment] 2021-03-16 19:48
+1 , I can confirm the same issue - reverting back to 4.2.8 fixed my issue.

**Comment by yc-yvonne** [comment] 2021-04-13 14:10
This is a duplicate of https://github.com/wwayne/react-tooltip/issues/677

**Comment by willemarcel** [comment] 2021-04-13 22:59
The 4.2.17 fixed this issue on my tests

**Comment by vova42matters** [comment] 2021-04-22 12:02
+1 for 4.2.17

**Closed** 2022-12-07 12:40 UTC
