### ISSUE TITLE
after rebinding all tooltips by ReactTooltip.rebuild() but elements which have been deleted "data-tip" attribute still work

### ISSUE THREAD

**Issue by gameforlife2710** [ReactTooltip/react-tooltip#274] opened 2017-03-21 07:16 UTC

**Comment by huumanoid** [comment] 2017-03-21 08:39
Yes, indeed. Thanks a lot for the report!

I propose you to set `data-tip-disable="true"` instead of removing `data-tip`.

If it doesn't help, please, wait for a patch.

**Comment by huumanoid** [comment] 2017-03-21 09:14
Well, not so fast. I can't reproduce this issue.

If `data-tip` is null or is empty, the tooltip wouldn't appear at all.

Are you sure that `data-tip` is deleted?
If you can, please, provide an example which reproduces this issue.

**Comment by huumanoid** [comment] 2017-03-28 19:20
Well, here are the test examples:
https://github.com/huumanoid/react-tooltip-issue-test/blob/master/src/remove-data-tip.jsx
http://hmnid.ru:8090/remove-data-tip

I know the reason of this issue, but I'm not sure we should fix it, because it would be automatically fixed as soon as #137 will be resolved

**Comment by danielbarion** [comment] 2022-11-09 16:10
Hi guys, closing due to age, we did some publishes recently, please try the latest one and if necessary, open a new issue, thanks!

**Closed by danielbarion** 2022-11-09 16:10 UTC
