### ISSUE TITLE
[BUG] The tooltip glitches when clicked, sometimes being shown correctly, sometimes don't.

### ISSUE THREAD

**Issue by tiagoberwanger** [ReactTooltip/react-tooltip#1100] opened 2023-10-04 00:57 UTC
**Bug description**
The tooltip glitches, sometimes being showed correctly, sometimes under the card.

**Version of Package**
v4.5.1

**To Reproduce**
I'm using the following method to obtain a clicable icon with the tooltip, which is rendered in the card showed below in the screenshot

```
getInCartCheck(quantityInCart) {
        if (quantityInCart > 0) {
            const labelText = quantityInCart > 1 ? `${quantityInCart} adicionados` : `${quantityInCart} adicionado`
            return (
                <span className={styles.inCartCheck} style={{ display: 'inline' }}>
                    <div data-for="inCart" data-tip={labelText} data-event="click">
                        <GreenCheckImage />
                    </div>
                    <ReactTooltip id="inCart" class={styles.inCartTooltip} effect="solid" globalEventOff="click" />
                </span>
            )
        }
    }
```

**Expected behavior** 
sometimes does work
![image](https://github.com/ReactTooltip/react-tooltip/assets/65252268/400ad2bf-8f96-4dac-8ed7-2940dc20db01)  

sometimes doesn't
![image](https://github.com/ReactTooltip/react-tooltip/assets/65252268/e1c9649e-c2e1-4eb5-b82c-2a1f195a60a9)  

**Attempts**
- Fix using z-index ❌ 
- Changing the styles from the tooltip ❌ 

**Desktop**
 - OS: MacOS
 - Browser: Chrome 117.0.5938.132 
 - Framework: React v16

**Additional context**
This is the development ambient, if needed I can provide more information. 
Hope someone can help :)
Thanks!

**Comment by gabrieljablonski** [comment] 2023-10-04 01:10
Hi @tiagoberwanger.

V4 has been deprecated and we don't really maintain it any longer.

The best we can do is if you can provide a sample project (repo, codesandbox, etc...) reproducing the issue, we can make some suggestions on how to work around it.

**Comment by gabrieljablonski** [comment] 2023-10-04 13:31
I found #712, which seems to be similar to your problem.

From the code structure, it seems `getInCartCheck()` can get called multiple times, is that correct? If so, you're creating multiple tooltips with the same id, which might also be causing other issues.

As one of the comments in that issue suggests, try removing the tooltip from this section, and move it to a higher layer on your DOM, such that the `inCart` tooltip gets rendered only once. It also suggests putting the tooltip *after* all the other components, so try that too.

I'll close the issue but feel free to share your results.

**Closed by gabrieljablonski** 2023-10-04 13:31 UTC
Labels: Bug, V4
