### ISSUE TITLE
Arrow centering looks broken with v4.4.3

### ISSUE THREAD

**Issue by alexzel** [ReactTooltip/react-tooltip#809] opened 2022-10-28 05:59 UTC
Here is the difference between v4.4.2 and v4.4.3 with solid effect selected. See the vertical line I drew through the arrow center. I tested it in both FF and Chrome.

v4.4.2
![v4 4 2](https://user-images.githubusercontent.com/1964324/198512151-82de143a-6587-4f28-8b4c-73b1e222a61c.png)

v4.4.3
![v4 4 3](https://user-images.githubusercontent.com/1964324/198512156-f3d29045-cf85-4bd1-8fd9-e842ff0af24e.png)

I think it's related to the changes in this PR https://github.com/ReactTooltip/react-tooltip/pull/806
@erezcarmel @danielbarion

**Comment by danielbarion** [comment] 2022-10-28 12:10
Thanks for the report @alexzel! 

Can you or @erezcarmel do a PR to fix that one, please? I'll review it as soon as possible!

**Comment by danielbarion** [comment] 2022-11-09 14:23
Hi @alexzel, can you re-check using the version `v4.5.0` published today, please?

**Comment by alexzel** [comment] 2022-11-10 03:04
This one is not fixed yet.

![arrow-centering](https://user-images.githubusercontent.com/1964324/200990622-3a542cfd-fcc5-4991-892b-55c55431cbe4.png)

**Comment by danielbarion** [comment] 2022-11-14 12:07
Hmm, thanks for the explanation @a33068843, can you or @alexzel do a PR to fix this one, please?

**Comment by erezcarmel** [comment] 2022-11-23 09:07
@danielbarion I'm on it. Assign the issue to me.

**Comment by erezcarmel** [comment] 2022-11-23 10:38
Created PR [#824](https://github.com/ReactTooltip/react-tooltip/pull/824/)

**Comment by alexzel** [comment] 2022-11-25 07:07
Arrow centering looks good, but the changes seem to bring back previously fixed issue in https://github.com/ReactTooltip/react-tooltip/issues/810 I get the following when I try the same as in that issue description.

<img width="211" alt="Screen Shot 2022-11-24 at 11 05 28 PM" src="https://user-images.githubusercontent.com/1964324/203921565-00c10364-63e6-4478-951a-801d7b3a5798.png">

**Comment by danielbarion** [comment] 2022-11-25 11:48
Oh 😢 
Can someone do a fix for this again, please?
I'm using all my available time in V5 of react-tooltip

**Comment by erezcarmel** [comment] 2022-11-29 09:46
@danielbarion I can't reproduce it in my environment.
@alexzel Are you sure you pulled the latest version?

<img width="259" alt="Screen Shot 2022-11-29 at 11 10 55" src="https://user-images.githubusercontent.com/6206431/204495268-91fcb028-a125-45ef-8d83-b6cbf926bd81.png">

**Comment by danielbarion** [comment] 2022-11-30 21:21
Please, take a look at https://react-tooltip.com/docs/examples/basic-examples

And let me know your thoughts, thanks!

**Comment by danielbarion** [comment] 2022-12-07 12:36
Closing all v4 issues due to V5 released.

If necessary, please open a new issue using V5, thanks!

**Closed by danielbarion** 2022-12-07 12:36 UTC
Labels: Bug, help wanted
