### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Karan09542** [ReactTooltip/react-tooltip#1231] opened 2024-10-28 04:29 UTC
const [more, setMore] = useState(false)
state work right:

-----------------------
"more" value also change But?
problem is that - if more changes then true condition of "more" is render(toggle) but not false condition | our mean is that false condition not toggle it remains as it was
## simple says: if 'more' condition is false then both render simulteneously

![image](https://github.com/user-attachments/assets/7d78b57a-8e95-44e4-8128-ea6f28a14ad1)

we try different way but it not work like this: 
true condition toggle => if condition false then both render together

`more ? <Tooltip render-something />: <Tooltip render-anotherSomething />`
`
on asking chat gpt then he say use => useEffect  but not work then it SAYS

If the tooltip content is still not updating dynamically based on the more state, the tooltip library might indeed be caching the content or not re-rendering as expected.

It sounds like your tooltip content isn't updating when the more state changes. This often happens when the component using the render function doesn't re-render on state updates or when the tooltip library caches the content based on initial render values.

these are image:

![image](https://github.com/user-attachments/assets/44b4eb64-7874-44d3-8c21-fdcd6765cd94)
![image](https://github.com/user-attachments/assets/5743b458-24fe-45fc-bc69-57c26f250965)

# one more issue also happening 
when using this on any element then a border surrounds element dark dark border its seem like a outline come in non form element
![image](https://github.com/user-attachments/assets/abe265dd-8db5-4f4c-9574-22332c5b1c8d)

# सीताराम हर हर महादेव

**Comment by Karan09542** [comment] 2024-11-10 08:39
> @Karan09542 please check: https://codesandbox.io/p/sandbox/gallant-leftpad-8kvtn7
> 
> It looks like the conditional rendering is working, can you please provide one codesandbox with the issue so I can reproduce it and verify?

when i write  the same code  for codesandbox for that issue then we see all thing work well
i think the component inside we using this react-tooltip having some issue that's why it is not work properly

so , sorry for that

# But we Analyse something that may cause of this issue why Tooltip not work properly in that component 
<TooltipExample/> work correctly but again we using two or more

**Comment by danielbarion** [comment] 2024-11-10 14:04
Since it's not an issue with the react-tooltip (as the issue was not reproducible through the example), I'll be closing this issue, please feel free to open a new one when you have the reproducible example.

Thanks!

**Closed by danielbarion** 2024-11-10 14:04 UTC
Labels: Bug, Information Needed
